version: 2

workflows:
  version: 2
  default_workflow:
    jobs:
      - update_doc:
          filters:
            branches:
              only: dev


jobs:
  update_doc:
    working_directory: ~/workdir
    docker:
      - image: circleci/node:10.15.1-browsers
    steps:
      - checkout
      - run:
          name: Update app
          command: |
            git clone -q --depth 1 https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/.cyber.git
      - deploy:
          name: Update app from .cyber repo
          working_directory: ~/workdir/distribution/client
          command: |
            rm -rf build/
            yarn install
            yarn build
            cd build
            git init
            git config user.email "cybercongress42@gmail.com"
            git config user.name "Cyber Admin"
            git add .
            git commit -m "Circle CI: Update Site [skip ci]"
            git push -q -f https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/.cyber.git dev:gh-pages
#