version: 2

workflows:
  version: 2
  default_workflow:
    jobs:
      - build_cyb:
          filters:
            branches:
              only: master
      
jobs:
  build_cyb:
    working_directory: ~/workdir
    docker:
      - image: circleci/node:14.16.0-browsers
    steps:
      - checkout
      - run:
          name: Update app
          command: |
            git clone -q --depth 1 https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/cyb.git
      - deploy:
          name: Build app from production branch
          working_directory: ~/workdir
          command: |
            rm -rf build/
            yarn install
            yarn build
            cd build
            git init
            echo "cyb.ai" > CNAME
            git config user.email "cybercongress42@gmail.com"
            git config user.name "Cyber Admin"
            git add --all
            git commit -m "Circle CI: update cyb build [skip ci]"
            git push -q -f https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/dot-cyber.git master:build
