version: 2

workflows:
  version: 2
  default_workflow:
    jobs:
      - update_distribution_app:
          filters:
            branches:
              only: dev


jobs:
  update_distribution_app:
    working_directory: ~/workdir
    docker:
      - image: circleci/node:12.14.0-browsers
    steps:
      - checkout
      - run:
          name: Update app
          command: |
            git clone -q --depth 1 https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/dot-cyber.git
      - deploy:
          name: Update app from dot-cyber repo
          working_directory: ~/workdir
          command: |
            rm -rf build/
            yarn install
            yarn build
            cd build
            git init
            echo "rebyc.cyber.page" > CNAME
            git config user.email "cybercongress42@gmail.com"
            git config user.name "Cyber Admin"
            git add --all
            git commit -m "Circle CI: Update Site [skip ci]"
            git push -q -f https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/dot-cyber.git master:gh-pages
